# Generated by Django 3.2.4 on 2021-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='term1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='term2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='term3',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
